features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
slideshow_display: 0
slide1_image: {  }
slide2_image: {  }
slide3_image: {  }
